package com.mfsimanski.invoiceViewer.model;

import java.util.Objects;

// Generated May 6, 2020, 12:08:22 PM by Hibernate Tools 5.4.14.Final

/**
 * InvoiceItemId generated by hbm2java
 */
public class InvoiceItemId implements java.io.Serializable
{

	private int invoiceNumber;
	private Customer customer;

	public InvoiceItemId()
	{
	}

	public InvoiceItemId(int invoiceNumber, Customer customer)
	{
		this.invoiceNumber = invoiceNumber;
		this.customer = customer;
	}

	public int getInvoiceNumber()
	{
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(int invoiceNumber)
	{
		this.invoiceNumber = invoiceNumber;
	}

	public Customer getServiceId()
	{
		return this.customer;
	}

	public void setServiceId(Customer customer)
	{
		this.customer = customer;
	}

	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvoiceItemId))
			return false;
		InvoiceItemId castOther = (InvoiceItemId) other;

		return (this.getInvoiceNumber() == castOther.getInvoiceNumber())
				&& (this.getServiceId() == castOther.getServiceId());
	}

	public int hashCode()
	{
		int result = 17;

		result = 37 * result + this.getInvoiceNumber();
		result = 37 * result + Objects.hashCode(this.getServiceId());
		return result;
	}

}
