package com.mfsimanski.invoiceViewer.model;
// Generated May 6, 2020, 12:08:22 PM by Hibernate Tools 5.4.14.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Invoice generated by hbm2java
 */
@Entity
@IdClass(InvoiceItemId.class)
@Table(name = "INVOICE")
public class Invoice implements Serializable
{
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	public int invoiceNumber;
	
	@Id
	public Customer customer;
	
	public String dateIn;
	public String dateOut;
	@Column(precision=6, scale=2)
	public BigDecimal subtotal;
	@Column(precision=6, scale=2)
	public BigDecimal tax;
	@Column(precision=6, scale=2)
	public BigDecimal totalAmount;

	public Invoice(int invoiceNumber, Customer customer, String dateIn, String dateOut, BigDecimal subtotal,
			BigDecimal tax, BigDecimal totalAmount)
	{
		super();
		this.invoiceNumber = invoiceNumber;
		this.customer = customer;
		this.dateIn = dateIn;
		this.dateOut = dateOut;
		this.subtotal = subtotal;
		this.tax = tax;
		this.totalAmount = totalAmount;
	}

	public int getInvoiceNumber()
	{
		return invoiceNumber;
	}

	public void setInvoiceNumber(int invoiceNumber)
	{
		this.invoiceNumber = invoiceNumber;
	}

	public Customer getCustomer()
	{
		return customer;
	}

	public void setCustomer(Customer customer)
	{
		this.customer = customer;
	}

	public String getDateIn()
	{
		return dateIn;
	}

	public void setDateIn(String dateIn)
	{
		this.dateIn = dateIn;
	}

	public String getDateOut()
	{
		return dateOut;
	}

	public void setDateOut(String dateOut)
	{
		this.dateOut = dateOut;
	}

	public BigDecimal getSubtotal()
	{
		return subtotal;
	}

	public void setSubtotal(BigDecimal subtotal)
	{
		this.subtotal = subtotal;
	}

	public BigDecimal getTax()
	{
		return tax;
	}

	public void setTax(BigDecimal tax)
	{
		this.tax = tax;
	}

	public BigDecimal getTotalAmount()
	{
		return totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount)
	{
		this.totalAmount = totalAmount;
	}
}
